name: Build and Release Python Package

on:
  push:
    tags:
      - 'v*'  # Déclenché lorsqu'un tag commençant par 'v' est poussé

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Récupérer tout l'historique pour les tags
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install uv
        uses: astral-sh/setup-uv@v1 [[5]]
        with:
          uv-version: 'latest'
      
      - name: Build package with uv
        run: |
          uv pip install build [[2]]
          uv pip run build
      
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.get_version.outputs.VERSION }}
          files: |
            dist/*.tar.gz
            dist/*.whl
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
