name: Validate commit with pytest

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Récupérer tout l'historique pour les tags
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          uv-version: 'latest'
      
      - name: Build package with uv
        run: |
          uv python install
          uv sync
          uv run pytest      
